<?php
/**
 * @file
 * Code for the Costbenefit module.
 */

/**
 * Implements hook_menu().
 */
function costbenefit_menu() {
  $items = array();
  $items['home'] = array(
    'page callback' => 'costbenefit_home_page',
    'access callback' => TRUE,
    'file' => 'costbenefit.pages.inc',
  );
  $items['cb/%costbenefit'] = array(
    'title callback' => 'costbenefit_get_title',
    'title arguments' => array(1),
    'page callback' => 'costbenefit_view_entity',
    'page arguments' => array(1),
    //@todo: Access callback to only allow authors.
    'access callback' => 'user_is_logged_in',
  );
  $items['cb/%costbenefit/edit'] = array(
    'title callback' => 'costbenefit_get_title',
    'title arguments' => array(1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('costbenefit_form', 1),
    //@todo: Access callback to only allow authors.
    'access callback' => 'user_is_logged_in',
    'file' => 'costbenefit.forms.inc',
  );
  $items['cb/add'] = array(
    'title' => 'New Cost-Benefit Matrix',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('costbenefit_form', NULL),
    'access callback' => 'user_is_logged_in',
    'file' => 'costbenefit.forms.inc',
  );
  return $items;
}

/**
 * Implements hook_entity_info().
 */
function costbenefit_entity_info() {
  $info = array();
  $info['costbenefit'] = array(
    'label' => t('Cost-Benefit'),
    'base table' => 'costbenefit',
    'entity keys' => array(
      'id' => 'cb_id',
      'label' => 'title',
    ),
    'entity class' => 'CostbenefitEntity',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'CostbenefitEntityController',
    'module' => 'costbenefit',
  );
  return $info;
}

/**
 * Menu autoloader for /costbenefit.
 */
function costbenefit_load($cb_id) {
  $entity = entity_load('costbenefit', array($cb_id));
  return array_pop($entity);
}

/**
 * Page callback for /costbenefit/ID.
 */
function costbenefit_view_entity($entity) {
  return entity_view('costbenefit', array($entity->cb_id => $entity), 'full');
}

/**
 * Title callback for /costbenefit/ID.
 */
function costbenefit_get_title($entity) {
  return $entity->title;
}
